### PR TITLE
RDEV-7371 - Upgrade to avalonia 11

### PR DESCRIPTION
**Pull request by joaompneves**

### CODE REVIEW

**Review by alvesmiguel1 — APPROVED** [review]

**Comment by xubo-magictavern-com** [comment]
I try to use this webview, found exception, launch failed.

On branch avalonia11，it was launch failed with exception:

System.InvalidOperationException: Unable to create child window for native control host. Application manifest with supported OS list might be required.
   at Avalonia.Win32.Win32NativeControlHost.DumbWindow..ctor(Boolean layered, Nullable`1 parent) in /_/src/Windows/Avalonia.Win32/Win32NativeControlHost.cs:line 99
   at Avalonia.Win32.Win32NativeControlHost.CreateNewAttachment(Func`2 create) in /_/src/Windows/Avalonia.Win32/Win32NativeControlHost.cs:line 35
   at Avalonia.Controls.NativeControlHost.UpdateHost() in /_/src/Avalonia.Controls/NativeControlHost.cs:line 91
   at Avalonia.Controls.NativeControlHost.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/NativeControlHost.cs:line 34

position is 
static void Main(string[] args) {
            AppBuilder.Configure<App>()
                      .UsePlatformDetect()
                      .UseReactiveUI()
                      .StartWithClassicDesktopLifetime(args);
        }

**Comment by Sunny-Game** [comment]
I try to use this webview, found exception, launch failed.

On branch avalonia11，it was launch failed with exception:

System.InvalidOperationException: Unable to create child window for native control host. Application manifest with supported OS list might be required.
at Avalonia.Win32.Win32NativeControlHost.DumbWindow..ctor(Boolean layered, Nullable1 parent) in /_/src/Windows/Avalonia.Win32/Win32NativeControlHost.cs:line 99 at Avalonia.Win32.Win32NativeControlHost.CreateNewAttachment(Func2 create) in //src/Windows/Avalonia.Win32/Win32NativeControlHost.cs:line 35
at Avalonia.Controls.NativeControlHost.UpdateHost() in //src/Avalonia.Controls/NativeControlHost.cs:line 91
at Avalonia.Controls.NativeControlHost.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/NativeControlHost.cs:line 34

position is
static void Main(string[] args) {
AppBuilder.Configure()
.UsePlatformDetect()
.UseReactiveUI()
.StartWithClassicDesktopLifetime(args);
}

**Comment by schnerring** [comment]
Is any help required to move this forward? Currently on v11, and I can't get the web view to work.

**Comment by schnerring** [comment]
My bad, I didn't see that there's a v11 NuGet package available: 

```xml
<PackageReference Include="WebViewControl-Avalonia" Version="2.106.10-avalonia11" />
```

Would be nice to install this by default, now that v11 is stable.

**Pull request merged**
